config/routes.rb
Redesneurais::Application.routes.draw do
  resources :pessoas
  root :to => 'inicio#index'

  match "/salva_tabela" => "inicio#salva_tabela"
  match "/show_tabela" => "inicio#show_tabela"
  match "/destroi_tabela" => "inicio#destroi_tabela"
  match "/salva_targets" => "inicio#salva_targets"
  match "/treino" => "treino#treino_tabela"
  match "/treinar_tabela" => "treino#treinar"
  match "/testar_rede" => "treino#testar"
  match "/caracteres" => "caracteres#index"
  match "/salva_letra" => "caracteres#salva_letra"
  match "/show_letra" => "caracteres#show"


end

app/models/pessoa.rb
# -*- encoding : utf-8 -*-
class Pessoa
  include MongoMapper::Document

  key :nome, String
  key :email, String

end

app/models/tabela_verdade.rb
# -*- encoding : utf-8 -*-
class TabelaVerdade
	include MongoMapper::Document
	key :nome, String
	key :vars, Integer
	key :linhas, Array
	key :saida_esperada, Array
	key :letra, Boolean

	one :treino_tabela

	def letra?
		letra
	end

end

app/models/treino_tabela.rb
# -*- encoding : utf-8 -*-
class TreinoTabela
	include MongoMapper::Document
	key :tabela_treino, Array
	key :pesos, Array	

	belongs_to :tabela_verdade

	def treinar
		tabela_completa = Array.new
		deltaWtotal = Array.new
		wtotal = Array.new
		vars = self.tabela_verdade.vars+1
		anterioresLinha = Array.new(vars){0}
		linhas = self.tabela_verdade.linhas
		targets = self.tabela_verdade.saida_esperada

		for i in 0..(linhas.size-1)
			linhaDeltaW = []
			linhaW = []
			for j in 0..(linhas[i].size-1)
				deltaW = linhas[i][j]*targets[i]
				linhaDeltaW << deltaW
				w = anterioresLinha[j]+deltaW
				anterioresLinha[j] = w
				linhaW << w
			end
			deltaWtotal << linhaDeltaW
			wtotal << linhaW
			tabela_completa << (linhaDeltaW + linhaW)
		end
		self.pesos = wtotal.last
		self.tabela_treino = tabela_completa
		self.save
	end

	def treinar_letra
		tabela_completa = Array.new
		deltaWtotal = Array.new
		wtotal = Array.new
		vars = self.tabela_verdade.vars+1
		anterioresLinha = Array.new(vars){0}
		linha = self.tabela_verdade.linhas
		target = self.tabela_verdade.saida_esperada[0]

		for i in 0..(linha.size-1)
			linhaDeltaW = []
			linhaW = []
			deltaW = linha[i]*target
			deltaWtotal << deltaW
			w = anterioresLinha[i]+deltaW
			wtotal << w
		end
		tabela_completa = (deltaWtotal + wtotal)
		self.pesos = wtotal
		self.tabela_treino = tabela_completa
		self.save
		
	end

	def testar
		linhas = self.tabela_verdade.linhas
		limiar = 0
		net = Array.new
		saida = Array.new
		pesos = self.pesos
		for i in 0..(linhas.size-1)
			soma = 0
			for j in 0..(linhas[i].size-1)
				soma += linhas[i][j]*pesos[j]
			end
			net << soma
			if soma < limiar
				s = -1
			else
				s = 1
			end
			saida << s
		end
		return net, saida
	end

	def testar_letra arrayEntrada
		linhas = arrayEntrada
		limiar = 20
		net = Array.new
		saida = Array.new
		pesos = self.pesos
		soma = 0
		for j in 0..(linhas.size-1)
			soma += linhas[j]*pesos[j]
		end
		net << soma
		if soma < limiar
			s = -1
		else
			s = 1
		end
		saida << s
		return net, saida
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/caracteres_controller.rb
# -*- encoding : utf-8 -*-
class CaracteresController < ApplicationController

	def index
		@letras = TabelaVerdade.where(letra: true).all
	end

	def salva_letra
		linha = Array.new
		linha = params[:linha]
		linha = linha.map{|x| x.to_i}
		linha << 1
		@letra = TabelaVerdade.new(
				letra: true,
				linhas: linha,
				nome: params[:nome],
				saida_esperada: [1],
				vars: 25
			)
		@letra.treino_tabela = TreinoTabela.new
		@letra.save
		respond_to do |format|
			format.json{render json: {id: @letra.id}}
		end
	end

	def show
		@letra = TabelaVerdade.find params[:id]
	end
end

app/controllers/inicio_controller.rb
# -*- encoding : utf-8 -*-
class InicioController < ApplicationController

	def index
		@tabela = TabelaVerdade.all
	end

	def salva_tabela
		@tabela = TabelaVerdade.new(vars: params[:vars], nome: params[:nome])
		@tabela.linhas = cria_linhas_tabela @tabela.vars
		@tabela.treino_tabela = TreinoTabela.new
		@tabela.save
		redirect_to :back
	end

	def show_tabela
		@tabela = TabelaVerdade.find params[:id]
	end

	def cria_linhas_tabela vars
		nl = 2**vars
		tabela = Array.new
		for num in 0..(nl-1) do
		   linha = Array.new
		   string = sprintf "%0#{vars}b", num
		   string.each_char do |c| linha << c.to_i end
		   linha = linha.map{|x| x == 0 ? x = -1 : x}
		   linha << 1
		   tabela << linha
		end
		return tabela
	end

	def salva_targets
		@tabela = TabelaVerdade.find params[:id]
		targets = params[:target].map{|x| x.to_i}
		@tabela.saida_esperada = targets
		@tabela.save
		redirect_to controller: :treino, action: :treino_tabela, id: @tabela.id
	end

	def destroi_tabela
		@tabela = TabelaVerdade.find params[:id]
		@tabela.destroy
		redirect_to :back
	end
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  # GET /pessoas
  # GET /pessoas.json
  def index
    @pessoas = Pessoa.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pessoas }
    end
  end

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
    @pessoa = Pessoa.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pessoa }
    end
  end

  # GET /pessoas/new
  # GET /pessoas/new.json
  def new
    @pessoa = Pessoa.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pessoa }
    end
  end

  # GET /pessoas/1/edit
  def edit
    @pessoa = Pessoa.find(params[:id])
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(params[:pessoa])

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully created.' }
        format.json { render json: @pessoa, status: :created, location: @pessoa }
      else
        format.html { render action: "new" }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pessoas/1
  # PUT /pessoas/1.json
  def update
    @pessoa = Pessoa.find(params[:id])

    respond_to do |format|
      if @pessoa.update_attributes(params[:pessoa])
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa = Pessoa.find(params[:id])
    @pessoa.destroy

    respond_to do |format|
      format.html { redirect_to pessoas_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/treino_controller.rb
# -*- encoding : utf-8 -*-
class TreinoController < ApplicationController

	def treino_tabela
		@tabela = TabelaVerdade.find params[:id]
	end

	def treinar
		@tabela = TabelaVerdade.find params[:id]
		if @tabela.letra?
			@tabela.treino_tabela.treinar_letra
		else
			@tabela.treino_tabela.treinar
		end
		@tabela_treino = @tabela.treino_tabela.tabela_treino
		@vars = @tabela.vars
		@tabela.save
	end

	def testar
		@tabela = TabelaVerdade.find params[:id]
		if @tabela.letra?
			arg = params[:linha].map{|x| x.to_i}
			@net, @saida = @tabela.treino_tabela.testar_letra arg
		else
			@net, @saida = @tabela.treino_tabela.testar
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/views/caracteres/index.html.erb
<div id = "salva_letra">
    <% for i in 0..4 %>
        <%for j in 0..4%>
            <input type="checkbox" class="letra" linha="<%= i%>" coluna="<%= j%>">
            <%if j==4 %>
                <br />
            <%end%>
        <%end%>
    <%end%>
    <%= select("letra", i, ["X", "O"], {:include_blank => true}, {:class => 'letras'}) %>
    <input type="button" class="submit_letra" value="Salvar Letra"  >
</div>

<script type="text/javascript">
    $(document).ready(function(){
        var caracteres = new Array();
        $(".submit_letra").click(function(){
            caracteres = [];
            $(".letra").each(function(index, e){
                if($(e).is(':checked')){
                    caracteres.push(1);
                }else{
                    caracteres.push(-1);
                }
            });
            var nome = $(".letras").val();
            $.post("/salva_letra",{nome: nome ,linha: caracteres}, function(data){
                window.location = "/show_letra?id="+data.id
            });
        });
    });
</script>

app/views/caracteres/show.html.erb
<h1><%= @letra.nome%></h1>
<br />
<table id="rounded-corner">
	<tr>
		<% for num in 1..25%>
	  		<th><%= (num.to_s)%></th>
	  	<%end%>
	  	<th>Bias</th>
	  	<th>Target</th>
	</tr>
	<tr>
		<% @letra.linhas.each do |linha|%>
			<td><%= linha%></td>
		<%end%>
		<td><%= @letra.saida_esperada.first%></td>
	</tr>
</table>
<%if !@letra.treino_tabela.tabela_treino.empty?%>
	<table id="rounded-corner">
		<tr>
			<% for num in 1..@letra.vars%>
		  		<th><%= ("deltaW"+num.to_s)%></th>
		  	<%end%>
		  	<th>deltaBias</th>
		  	<% for num in 1..@letra.vars%>
		  		<th><%= ("W"+num.to_s)%></th>
		  	<%end%>
		  	<th>Bias</th>
		</tr>
		<tr>
		<% @letra.treino_tabela.tabela_treino.each do |linha|%>
		 	<td><%= linha%></td>
		<%end%>
		</tr>
	</table>
<%end%>
<%= link_to "Página inicial", "/", :class => "inicio"%>
<div id = "resultado"></div>
<div id="form_teste" style="display:none;"></div>
<div id = "teste_tabela">
	<div id = "salva_letra" style="width: 120px;">
	    <% for i in 0..4 %>
	        <%for j in 0..4%>
	            <input type="checkbox" class="letra" linha="<%= i%>" coluna="<%= j%>">
	            <%if j==4 %>
	                <br />
	            <%end%>
	        <%end%>
	    <%end%>
	    <input type="button" class="testar_letra" value="Testar Letra">
	</div>
	<div id ="resultado_teste" class="teste_letra"></div>
</div>
<input type="button" value="Testar Rede" id="testar_rede" class="comandos"/>
<input type="button" value="Treinar Rede" id="treinar_rede" class="comandos" />


<script type="text/javascript">
	$(document).ready(function(){
		$(document).ready(function(){
			$("#treinar_rede").click(function(){
				treinar_rede();
			});
			$(".testar_letra").click(function(){
				testar_rede();
			});
			treinar_rede = function(){
				var id = "<%=raw @letra.id%>"
				$.post("/treinar_tabela",{id:id}, function(data){
					$("#resultado").html(data);
					$("#testar_rede").show();
					$("#treinar_rede").hide();
					$("#form_teste").show();
				});
			}
			testar_rede = function(){
				var caracteres = new Array();
	           	caracteres = [];
	           	$(".letra").each(function(index, e){
	           	    if($(e).is(':checked')){
	          	        caracteres.push(1);
	            	}else{
	                   caracteres.push(-1);
	                }
	            });
	            caracteres.push(1);
	            var id = "<%=raw @letra.id%>"
	            $.post("/testar_rede",{id:id, linha: caracteres}, function(data){
	                $("#resultado_teste").html(data);
	            });
			}
		});		
	});	
</script>

app/views/inicio/index.html.erb
<h1>Treinamento de redes através da Teoria Hebbiana</h1>
<h2>Trabalho desenvolvido pelos alunos Lucas Costa Silva Simonini e Aline Gonçalves Fernandes</h2>
<h3>Instruções: </h3>
<ul>
  <li>Digite o nome da tabela e o número de variáveis de entrada e clique em "Criar tabela";</li>
  <li>Clique no link "Definir" para entrar com as saídas desejadas ou "Apagar" para deletar a tabela;</li>
  <li>Escolha as saídas desejadas e clique em "Salvar";</li>
  <li>Clique no botão "Treinar Rede" que aparecerá na tela;</li>
  <li>Após ser gerada a tabela de treino, clique em "Testar Rede" para verificar as saídas da rede definida;</li>
  <li>Obs: a tabela de treino não é salva mas pode ser gerada a qualquer momento!</li>
</ul>
<h2>Tabelas salvas</h2>
<table id = "index_tabelas">
  <tr>
    <th>Nome</th>
    <th></th>
  </tr>

<% @tabela.each do |tabela| %>
  <tr>
    <td><%= tabela.nome %></td>
    <td>
    	<%if tabela.saida_esperada.empty?%>
    		<%= link_to "Definir", "/show_tabela?id=#{tabela.id}"%>
    	<%else%>
        <% if tabela.letra?%>
          <%= link_to "Treinar rede", "/show_letra?id=#{tabela.id}"%>
        <%else%>
    		  <%= link_to "Treinar rede", "/treino?id=#{tabela.id}"%>
        <%end%>
    	<%end%>
    </td>
    <td><%= link_to "Apagar", "/destroi_tabela?id=#{tabela.id}"%></td>
  </tr>
<% end %>
</table>

<br />

<div id="criaTabela">
	<%=form_tag '/salva_tabela' do %>
	  
	  <div class="input campo">
		  <%= label_tag(:labelNome, "Nome da tabela: ") %> 
		  <%= text_field_tag(:nome) %>
	  </div>
	  <div class="input campo">
		  <%= label_tag(:labelVars, "Número de variáveis:") %> 
		  <%= number_field_tag(:vars, nil, :in => 1...11) %>
	  </div>
	  	<div class='submitContato'><%=submit_tag 'Criar tabela', :id => 'envia', :class => "cria_tabela"%></div>
	  <br/>
		
	<% end %>
</div>

<div id = "salva_letra">
    <% for i in 0..4 %>
        <%for j in 0..4%>
            <input type="checkbox" class="letra" linha="<%= i%>" coluna="<%= j%>">
            <%if j==4 %>
                <br />
            <%end%>
        <%end%>
    <%end%>
    <%= select("letra", i, ["X", "O"], {:include_blank => true}, {:class => 'letras'}) %>
    <input type="button" class="submit_letra" value="Salvar Letra"  >
</div>

<script type="text/javascript">
    $(document).ready(function(){
        var caracteres = new Array();
        $(".submit_letra").click(function(){
            caracteres = [];
            $(".letra").each(function(index, e){
                if($(e).is(':checked')){
                    caracteres.push(1);
                }else{
                    caracteres.push(-1);
                }
            });
            var nome = $(".letras").val();
            $.post("/salva_letra",{nome: nome ,linha: caracteres}, function(data){
                // window.location = "/show_letra?id="+data.id
                location.reload();
            });
        });
    });
</script>

app/views/inicio/show_tabela.html.erb
<h1><%= @tabela.nome%></h1>
<h3>Variáveis de entrada: <%= @tabela.vars%></h3>
<br />
<table id="rounded-corner">
	<tr>
		<% for num in 1..@tabela.vars%>
	  		<th><%= ("X"+num.to_s)%></th>
	  	<%end%>
	  	<th>Bias</th>
	  	<th>Target</th>
	</tr>
	<% @tabela.linhas.each_with_index do |linha, i|%>
	 <tr>
	 	<%linha.each do |l|%>
	 		<td><%= l%></td>
	 	<%end%>
	 	<td><%= select("t", i, [-1, 1], {:include_blank => true}, {:class => 'targets'}) %></td>
	</tr>
	<%end%>
</table>
<input type="button" value="Salvar Saídas" id="salva_targets" class="comandos"/>
<%= link_to "Página inicial", "/", :class => "inicio"%>

<div id="treino"></div>

<script type="text/javascript">
	$(document).ready(function(){
		$("#salva_targets").click(function(){
			var targets = new Array();
			targets = selecionaTargets();
			salva_targets(targets);
		});
	});

	selecionaTargets = function(){
		var targets = new Array();
		$('.targets').each(function(){
			targets.push($(this).val());
		});
		return targets
	}

	salva_targets = function(targets){
		var id = "<%=raw @tabela.id%>"
		$.post("/salva_targets",{id:id, target:targets}, function(data){
			window.location = "/treino?id="+id
		});
	}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Redesneurais</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pessoas/_form.html.erb
<%= form_for(@pessoa) do |f| %>
  <% if @pessoa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h2>

      <ul>
      <% @pessoa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pessoas/edit.html.erb
<h1>Editing pessoa</h1>

<%= render 'form' %>

<%= link_to 'Show', @pessoa %> |
<%= link_to 'Back', pessoas_path %>

app/views/pessoas/index.html.erb
<h1>Listing pessoas</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pessoas.each do |pessoa| %>
  <tr>
    <td><%= pessoa.nome %></td>
    <td><%= pessoa.email %></td>
    <td><%= link_to 'Show', pessoa %></td>
    <td><%= link_to 'Edit', edit_pessoa_path(pessoa) %></td>
    <td><%= link_to 'Destroy', pessoa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pessoa', new_pessoa_path %>

app/views/pessoas/new.html.erb
<h1>New pessoa</h1>

<%= render 'form' %>

<%= link_to 'Back', pessoas_path %>

app/views/pessoas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @pessoa.nome %>
</p>

<p>
  <b>Email:</b>
  <%= @pessoa.email %>
</p>


<%= link_to 'Edit', edit_pessoa_path(@pessoa) %> |
<%= link_to 'Back', pessoas_path %>

app/views/treino/testar.html.erb
<table id="rounded-corner">
	<tr>
		<th>NET</th>
	  	<th>Saida</th>
	</tr>
	<% for i in 0..(@net.size-1)%>
	<tr>
	 	<td><%= @net[i]%></td>
	 	<td><%= @saida[i]%></td>
	</tr>
	<%end%>
</table>

app/views/treino/treinar.html.erb
<% if @tabela.letra?%>
	<table id="rounded-corner">
		<tr>
			<% for num in 1..@vars%>
		  		<th><%= ("deltaW"+num.to_s)%></th>
		  	<%end%>
		  	<th>deltaBias</th>
		  	<% for num in 1..@vars%>
		  		<th><%= ("W"+num.to_s)%></th>
		  	<%end%>
		  	<th>Bias</th>
		</tr>
		<tr>
		<% @tabela_treino.each do |linha|%>
		 	<td><%= linha%></td>
		<%end%>
		</tr>
	</table>
<%else%>
	<table id="rounded-corner">
		<tr>
			<% for num in 1..@vars%>
		  		<th><%= ("deltaW"+num.to_s)%></th>
		  	<%end%>
		  	<th>deltaBias</th>
		  	<% for num in 1..@vars%>
		  		<th><%= ("W"+num.to_s)%></th>
		  	<%end%>
		  	<th>Bias</th>
		</tr>
		<% @tabela_treino.each_with_index do |linha, i|%>
		<tr>
		 	<%linha.each do |l|%>
		 		<td><%= l%></td>
		 	<%end%>
		</tr>
		<%end%>
	</table>
<%end%>

app/views/treino/treino_tabela.html.erb
<h1><%= @tabela.nome%></h1>
<h3>Variáveis de entrada: <%= @tabela.vars%></h3>
<br />
<br />
<div id="tabela_salva" class="tabelas">
	<table id="rounded-corner">
		<tr>
			<% for num in 1..@tabela.vars%>
		  		<th><%= ("X"+num.to_s)%></th>
		  	<%end%>
		  	<th>Bias</th>
		  	<th>Target</th>
		</tr>
		<% @tabela.linhas.each_with_index do |linha, i|%>
		 <tr>
		 	<%linha.each do |l|%>
		 		<td><%= l%></td>
		 	<%end%>
		 	<td><%= @tabela.saida_esperada[i]%></td>
		</tr>
		<%end%>
	</table>
</div>
<div id="resultado" class="tabelas">
	<%if !@tabela.treino_tabela.tabela_treino.empty?
		 tabela_treino = @tabela.treino_tabela.tabela_treino%>
		<table id="rounded-corner">
			<tr>
				<% for num in 1..@tabela.vars%>
			  		<th><%= ("deltaW"+num.to_s)%></th>
			  	<%end%>
			  	<th>deltaBias</th>
			  	<% for num in 1..@tabela.vars%>
			  		<th><%= ("W"+num.to_s)%></th>
			  	<%end%>
			  	<th>Bias</th>
			</tr>
			<% tabela_treino.each_with_index do |linha, i|%>			
			 <tr>
			 	<%linha.each do |l|%>
			 		<td><%= l%></td>
			 	<%end%>
			</tr>
			<%end%>
		</table>
		</div>
		<input type="button" value="Testar Rede" id="testar_rede" class="comandos"/>
	<%else%>
	</div>
		<input type="button" value="Treinar Rede" id="treinar_rede" class="comandos" />
	<%end%>
<div id="teste_tabela"></div>
<input type="button" value="Testar Rede" id="testar_rede" style="display:none;" class="comandos"/>
<%= link_to "Página inicial", "/", :class => "inicio"%>

<script type="text/javascript">
	$(document).ready(function(){
		$("#treinar_rede").click(function(){
			treinar_rede();
		});
		$("#testar_rede").click(function(){
			testar_rede();
		});
		treinar_rede = function(){
			var id = "<%=raw @tabela.id%>"
			$.post("/treinar_tabela",{id:id}, function(data){
				$("#resultado").html(data);
				$("#testar_rede").show();
			});
		}
		testar_rede = function(){
			var id = "<%=raw @tabela.id%>"
			$.post("/testar_rede",{id:id}, function(data){
				$("#teste_tabela").html(data);
			});
		}
	});		
</script>